services:
  
  nginx:
    container_name: nginx
    build: ./srcs/nginx/.
    image: nginx:v1
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./srcs/wordpress/.
    image: wordpress:v1
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb/.
    image: mariadb:v1
    volumes:
      - mariadb:var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      option: bind
      device: /Users/mel-jira/Desktop/inception/srcs/wordpress

  mariadb:
      name: mariadb
      driver: local
      driver_opts:
        type: none
        option: bind
        device: /Users/mel-jira/Desktop/inception/srcs/mariadb

networks:
  inception:
    driver: bridge