services:
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:v1
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:v1
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:v1
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  redis:
    container_name: radis
    build: ./requirements/bonus/radis/
    image: redis:v1
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inception

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/
    image: ftp/v1
    restart: always
    ports:
      - "21:21"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
  
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:v1
    restart: always
    depends_on:
      - mariadb
    ports:
     - "8080:8080"
    networks:
      - inception

  static_page:
    container_name: static_page
    build: ./requirements/bonus/static_page/
    image: static_page:v1
    restart: always
    ports:
      - "80:80"
    networks:
      - inception
  
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/
    image: cadvisor:v1
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-jira/data/wordpress

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-jira/data/mariadb

networks:
  inception:
    driver: bridge