services:
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:v1
    ports:
      - "8080:8080"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:v1
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:v1
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-jira/data/wordpress

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mel-jira/data/mariadb

networks:
  inception:
    driver: bridge